# Generated by Django 4.0.1 on 2022-01-22 19:02

import Nady_System.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('brochu_url', models.CharField(blank=True, max_length=50, null=True)),
                ('test_volume', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AntiBiotic',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('for_child_pregnant', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ABO_system', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'Ab'), ('O', 'O')], max_length=2)),
                ('Rh_type', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighLow',
            fields=[
                ('name', models.CharField(choices=[('High', 'High'), ('Low', 'Low')], max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Comment', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Senstivity',
            fields=[
                ('name', models.CharField(choices=[('Strong', 'Strong'), ('Moderate', 'Mmderate'), ('Weak', 'Weak'), ('Very Weak', 'Very Weak')], max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('shortcuts', djongo.models.fields.ArrayField(model_container=Nady_System.models.ShortCutParameter)),
                ('units', models.ManyToManyField(to='Nady_System.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
