# Generated by Django 4.0.1 on 2022-01-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nady_System', '0001_initial'),
        ('Products', '0003_initial'),
        ('Utils', '0003_remove_product_brand_delete_brand_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='kat',
            name='serial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kats', to='Products.product'),
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Utils.address'),
        ),
        migrations.AlterUniqueTogether(
            name='bloodgroup',
            unique_together={('ABO_system', 'Rh_type')},
        ),
    ]
