# Generated by Django 4.0.1 on 2022-01-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utils', '0003_remove_product_brand_delete_brand_delete_product'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('national_id', models.SmallIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=50, unique=True)),
                ('family_name', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='Utils.job')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='Utils.gender')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted'), related_name='persons', to='Utils.title')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Persons.person')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Persons.person',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Persons.person')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Persons.person',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Persons.person')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Persons.person',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Persons.person')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Persons.person',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Persons.person')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Persons.person',),
        ),
    ]
