# Generated by Django 4.0.1 on 2022-01-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0003_remove_product_brand_delete_brand_delete_product'),
        ('Persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted FK'), related_name='persons', to='Utils.title'),
        ),
    ]
