# Generated by Django 4.0.1 on 2022-01-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0002_brand_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
