# Generated by Django 4.0.1 on 2022-01-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('logo_url', models.CharField(blank=True, max_length=100, null=True)),
                ('made_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='Utils.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('volume', models.PositiveSmallIntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
